runtime: nodejs16

instance_class: F2

env_variables:
  BUCKET_NAME: "robocode-ui"

handlers:
  - url: /
    static_files: dist/robocode-final/index.html
    upload: dist/robocode-final/index.html

  - url: /
    static_dir: dist/robocode-final
